version: '3'
networks:
    my_network:
        driver: bridge

services:
    postgres:
        image: postgres:latest
        container_name: 'postgres-db'
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        networks:
            - my_network
        ports:
            - '5432:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data  # Persistent storage
            - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql  # Runs on first start

    user:
        container_name: 'user-service'
        build: ./user
        env_file:
            - ./user/.env
        networks:
            - my_network
        depends_on:
            - postgres
        environment:
            DB_HOST: postgres-db
            DB_PORT: 5432
            DB_USER: postgres
            DB_PASS: postgres
            DB_NAME: postgres

    api-gateway:
        container_name: 'api-gateway'
        build: ./api-gateway
        networks:
            - my_network
        depends_on:
            - user

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - api-gateway
        networks:
            - my_network

volumes:
    postgres-data: 
